apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
spec:
  containers:
    - name: my-nginx-app
      image: aliahmedhasan/nginx-fci
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      